### ISSUE TITLE
Is v1.5.0 released?

### ISSUE THREAD

**Issue by madwort** [nevir/rubocop-rspec#103]
I saw a commit saying 1.5.0 release https://github.com/nevir/rubocop-rspec/commit/8d059081e70f5a04f8fd4cc391804c8c7e8a8f65 but it looks like it hasn't been tagged https://github.com/nevir/rubocop-rspec/releases - if it's ready, could you do this so that I can start using it more easily?
Thanks!

**Comment by jyaworski** [comment]
@madwort it may not be tagged, but it's on rubygems.org if that helps in the interim.

**Comment by madwort** [comment]
Ah, so it is, thanks.
