### ISSUE TITLE
RSpec/DescribeClass applies to view specs when using config.infer_spec_type_from_file_location!

### ISSUE THREAD

**Issue by jcoyne** [nevir/rubocop-rspec#110]
#90 only fixed it for when the spec is explictly tagged as being a view type.

**Comment by backus** [comment]
@jcoyne unless you have an idea of how to statically determine this configuration I'm going to close this as WONTFIX since the cop cannot know your RSpec configuration

**Comment by andyw8** [comment]
I agree, since inference is disabled by default after RSpec 3.
