### ISSUE TITLE
Cops should only inspect test files

### ISSUE THREAD

**Issue by mockdeep** [nevir/rubocop-rspec#115]
We have a `feature` method in our application code that causes `rubocop-rspec` to complain about using instance variables in our view templates. Seems like maybe some or all of the checks shouldn't be running on application code, only on spec files.

**Comment by backus** [comment]
I agree actually. I've been considering adding a guard clause to all cops that assert something like `spec` being present in the source file path for the current file being analyzed. This would mean that `spec/foo.rb` and `tests/foo_spec.rb` would be analyzed but we would not analyze files like `tests/foo_test.rb`. Would that work for you @mockdeep?

I realize this might change behavior for some people but I've personally never seen someone not put their rspec tests in a spec directory

**Comment by backus** [comment]
Rough example of what this looks like btw: https://github.com/backus/rubocop-devtools/blob/master/lib/rubocop/cop/devtools/mixin/rspec_only.rb

**Comment by andyw8** [comment]
Seems like the right thing to do. Should also slightly improve performance since irrelevant files won't be scanned.

**Comment by mockdeep** [comment]
@backus that sounds good. I don't know if there might be rules to be enforced on `spec_helper` or other adjacent files, but that might be a consideration, too.

**Comment by backus** [comment]
Rough thoughts on implementation:

* We probably need some non-cop specific configuration. Basically I will have to see if we can have users add configuration to [`AllCops`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L9) without interfering with either rubocop or end user configuration

* We should then have some configuration that allows the end user to specify an array of patterns for determining whether something is a spec file. Default would probably be like `[%r{_spec\.rb$}, %r{spec/}]`

  * We could ship with this being an empty array which would have translate to special behavior. If you don't specify any spec path patterns then we will just inspect all files. This would let us release this without having to do a major version bump I think

    * I'm not crazy about empty array encoding this behavior. Maybe we would want two configuration variables. Maybe `RSpec/InspectAllFiles` (defaults to `true`) and `RSpec/SpecPathPattern`

**Comment by backus** [comment]
@mockdeep try out master. I've updated all cops to be spec only. You can configure the patterns rubocop-rspec uses by setting a preference in `AllCops` (I explained in the README). Let me know if this fixes your problem

**Comment by mockdeep** [comment]
@backus looks like that did the trick. Thanks!
