### ISSUE TITLE
Refactor cops to use `def_node_matcher`

### ISSUE THREAD

**Issue by backus** [nevir/rubocop-rspec#117]
Looks like it is public API enough. From gitter:

> **John Backus @backus 11:44**
>
> @bbatsov or @alexdowad are you guys happy with def_node_matcher? I'm taking over as maintainer for rubocop-rspec and I'm interested in refactoring some of the cops to use def_node_matcher. Curious if it is considered semipublic api that rubocop extensions can reasonably use
>
> **Alex Dowad @alexdowad 13:21**
>
> @backus I'm happy with it, don't know what others think.
>
> **John Backus @backus 13:25**
>
> Cool
> If you haven't heard plans to replace it that is good enough for my first question
> Other question is basically "would you do a minor version bump if you changed the public API for it?"
>
> **Alex Dowad @alexdowad 13:33**
>
> @bbatsov chooses when to release new versions and what to call them. I believe he would do a minor version bump when changing the AST-pattern-matching API, if he knew that people were relying on it.

**Comment by bbatsov** [comment]
Pretty much what @alexdowad said.

**Comment by backus** [comment]
I've refactored enough cops with this that I'm happy with the changes. I'll only replace the remaining cops if I need to touch them for some reason
