### ISSUE TITLE
Please bump minor version when adding cops

### ISSUE THREAD

**Issue by jcoyne** [nevir/rubocop-rspec#145]
The 1.5.3 broke my suite because the NamedSubjectCop was introduced.  Please use semantic versioning and bump the minor release when you add a new feature (like a new cop). Thank you for all your hard work. This is a really helpful project.

**Comment by backus** [comment]
Will do. New to maintaining this project so sorry about that. Want me to do anything now or are you fine with me just closing this issue for now and following this policy in the future?

**Comment by jcoyne** [comment]
Up to you.  You could yank 1.5.3 and push 1.6, or just do the right thing in the future.

**Comment by backus** [comment]
Yanking sounds more painful. I'll just stick to minor version bumps in the future. Thanks for opening the issue
