### ISSUE TITLE
Prefer expect over should

### ISSUE THREAD

**Issue by dkniffin** [nevir/rubocop-rspec#146]
I'm quite surprised this doesn't already exist. Maybe I'm blind. Please let me know if this cop exists already, either in this gem, or core rubocop. I see one here that checks the text for the`it`s, but nothing for the actual code.

Example:

````ruby
# bad
subject.should eq(2)

# good
expect(subject).to eq(2)
````

**Comment by backus** [comment]
Hm so this *could* be a cop but you can probably resolve this with the RSpec configuration which disables `#should` along with [transpec](https://github.com/yujinakayama/transpec) (a really impressive tool) which should automatically let you convert `foo.should` to `expect(foo)`.

**Comment by dkniffin** [comment]
Oh, I didn't realize you could disable `should` in rspec's configs. I did recently use transpec on our codebase, and that's why I wanted this linter, to make sure we don't get any new shoulds. I'll look into that config option. Thanks!

**Comment by backus** [comment]
Great. Feel free to reopen after investigating that rspec configuration if you think this should still be a cop
