### ISSUE TITLE
Add a `OneExpectation` cop asserting no more than `expect` per test

### ISSUE THREAD

**Issue by backus** [nevir/rubocop-rspec#149]
Aim for one assertion per test.

### Bad

```ruby
it 'creates a new user' do
  user = create_user(attributes)

  expect(user.name).to eql('John')
  expect(user.age).to  eql(22)
  expect(user.role).to eql(:admin)
end
```

### OK

```ruby
subject { create_user }

its(:name) { should eql('John') }
its(:age)  { should eql(22)     }
its(:role) { should eql(:admin) }
```

### OK

```ruby
it 'creates a new user' do
  expect(create_user(attributes)).to have_attributes(
    name: 'John',
    age:  22,
    role: :admin
  )
end
```

### Better

```ruby
it 'creates a new user' do
  expect(create_user(attributes)).to eql(
    User.new(
      name: 'John',
      age:  22,
      role: :admin
    )
  )
end
```

Extracted from #40 (thanks @agrimm)

**Comment by agrimm** [comment]
Does it also verify that there's no fewer than one expect per test?

**Comment by backus** [comment]
It probably shouldn't in case you are using a custom matcher or something that contains an `expect`

**Comment by andyw8** [comment]
Even if you're using a custom matcher, you still normally have an `expect`.

I would also like a way to verify there's not zero expectations, but I don't think it's a critical part, maybe it could even be a separate cop. (but perhaps this cop should be called something like `MaximumOfOneExpectation`?)

**Comment by andyw8** [comment]
(Yes, people do unfortunately write tests that have no expectations – the failure case is often indicated by raising an exception).

**Comment by backus** [comment]
@andyw8 basically my concern is that this would be very error prone. Consider my [recent refactor adding `expect_violation`](https://github.com/nevir/rubocop-rspec/pull/142).

**Comment by backus** [comment]
Now we could track the number of methods inside of a test that are exactly `expect` and we could have an option that also looks for methods that contain the word `expect` or `assert` (so `expect_violation` would match). Basically though I'm just noting that it is impossible to do the "exactly one test" check perfect but we can employ a set of hacks / heuristics like these. This is the reality of static analysis with ruby though

**Comment by backus** [comment]
@agrimm this is implemented in master

**Comment by edslocomb** [comment]
I can see the value of this in unit testing, but can someone explain the rationale when applied to integration tests?  

We have quite a few feature specs that test multi-step sequences of user interaction, with expectations at many points in the process.

Are we supposed to be creating a context() block for every click_button() and visit_page() in the sequence?

**Comment by backus** [comment]
@edslocomb I don't see anything wrong with just disabling this cop for your integration test directory

**Comment by backus** [comment]
@edslocomb I was also considering adding functionality for this cop to treat expectations under [`aggregate_failures`](https://www.relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures) as one expectation which *could* also be a solution to your integration question. Would that be interesting to you? I can expand what I mean if you would like
