### ISSUE TITLE
Rubocop conflict.

### ISSUE THREAD

**Issue by KyleMacPherson** [nevir/rubocop-rspec#153]
Hey,

I am currently getting this error.

`Unable to activate rubocop-rspec-1.4.1, because rubocop-0.40.0 conflicts with rubocop (= 0.39.0)`

Is there a preferred version of rubocop I should use?

Thanks!

**Comment by backus** [comment]
Hm. Could you try out rubocop-rspec 1.6 and rubocop 0.42?

**Comment by backus** [comment]
@KyleMacPherson could you let me know if that resolves your issue?

**Comment by nijikon** [comment]
@KyleMacPherson up to and including version `1.4.1` we explicitly blocked `rubocop` to a particular version. If you can't upgrade `rubocop` to latest then `1.5.0` will work for you. If you can do what @backus suggested.

**Comment by backus** [comment]
@KyleMacPherson I'm going to close this just so I can stay on top of our issue count. Please reopen if @nijikon's advice didn't work and you're still having problems.
