### ISSUE TITLE
Check `expect` to provide actual value

### ISSUE THREAD

**Issue by geniou** [nevir/rubocop-rspec#17]
`expect` should contain the actual value, not the expected value. An idea would be to check for thinks like array, string and hash inside of `expect`.

https://www.relishapp.com/rspec/rspec-expectations/v/3-0/docs/built-in-matchers

**Comment by andyw8** [comment]
Could you give an example of what you mean?

**Comment by dkniffin** [comment]
I think the idea is that the object being tested should be inside of the `expect`, and not the expected value.

Ie:

````ruby
subject { 2 + 1 }

it 'works' do
  # bad
  expect(3).to eq(subject)

  # good
  expect(subject).to eq(3)
end
```

**Comment by geniou** [comment]
@dkniffin correct. Thanks.

**Comment by backus** [comment]
I'm planning on implementing this soon hopefully. This should be a fairly easy cop to implement. Basically, when a cop encounters `expect(...)`, it will check to see if the argument is one of many literal nodes (`(int)`, `(float)`, `(true)`, etc) or an array of only literals.

**Comment by backus** [comment]
@geniou this is implemented in master

**Comment by jcoyne** [comment]
The examples given in rspec-rails break this cop:

http://www.relishapp.com/rspec/rspec-rails/v/3-5/docs/routing-specs

**Comment by backus** [comment]
@jcoyne you should disable it for your routing specs then. The point of the cop is that most tests probably don't want to be making assertions about literal values so this cop helps detect when people have their expected and actual value mixed up
