### ISSUE TITLE
Cop Idea: no/max nested contexts

### ISSUE THREAD

**Issue by mockdeep** [nevir/rubocop-rspec#177]
Would love to have a cop which restricts the number of nested contexts allowed. It's generally a code smell when the nesting has to go deeper than 1:

```ruby
# bad
RSpec.describe 'foo' do
  context 'when that thing' do
    context 'when this other thing' do
      it 'does something'
    end
  end
end

# good
context 'when that thing' do
    it 'does something'
end
```

**Comment by andyw8** [comment]
This was just added recently, but hasn't yet been released:

https://github.com/nevir/rubocop-rspec/pull/156

**Comment by mockdeep** [comment]
Ah, cool. Thanks!
