### ISSUE TITLE
DEFAULT_FILE undefined when using debugging mode

### ISSUE THREAD

**Issue by shepmaster** [nevir/rubocop-rspec#179]
[Source](https://github.com/nevir/rubocop-rspec/blob/40e860dc8a45d42caa6debca28398792c6e3d061/lib/rubocop/rspec/inject.rb#L10):

```ruby
puts "configuration from #{DEFAULT_FILE}" if ConfigLoader.debug?
```

Looks like the issue was introduced in 8d03dbffe7ba7a4746ebe767779020eb5a7887fa

**Comment by backus** [comment]
Ah shoot good catch. Thanks

**Comment by backus** [comment]
Would accept a simple PR to fix this @shepmaster if you have a minute. Otherwise I might not be able to get to this for a bit
