### ISSUE TITLE
Release 1.7

### ISSUE THREAD

**Issue by backus** [nevir/rubocop-rspec#185]
@andyw8 @nijikon @geniou Any objections before I release 1.7? I ask since I've added a lot of new functionality since 1.6: https://github.com/nevir/rubocop-rspec/blob/master/CHANGELOG.md

I'll aim to release on Wednesday otherwise

**Comment by geniou** [comment]
Fine for me. Thanks for the big effort.

**Comment by backus** [comment]
Released!
