### ISSUE TITLE
Suggestion: Cop that disallows stubbing message chains

### ISSUE THREAD

**Issue by bquorning** [nevir/rubocop-rspec#186]
As [the RSpec documentation](https://relishapp.com/rspec/rspec-mocks/v/3-5/docs/working-with-legacy-code) says (with my emphasis):

> RSpec provides a few features that, while not generally recommended, can be useful when you are getting legacy code under test (or in similar situations). *Usage of these features should be considered a code smell*.
>
> 1. Any Instance
> 2. Message Chains

While rubocop-rspec already includes a cop checking against `allow_any_instance_of` etc., there is no cop checking against `stub_chain` and `receive_message_chain`.

**Comment by bquorning** [comment]
PR: #187.

**Comment by backus** [comment]
Good idea :)
