### ISSUE TITLE
described_class inside modules

### ISSUE THREAD

**Issue by stefanoverna** [nevir/rubocop-rspec#29]
I saw there's a pending test here https://github.com/nevir/rubocop-rspec/blob/master/spec/rubocop/cop/rspec/described_class_spec.rb#L89, great documentation btw, thanks for the effort!

I was wondering if and when the test will become green, as it's quite a frequent use-case in my code :) I'm totally new to rubocop.. I'm trying to study how to extend DescribedClass cop, but I'm not sure I will come up with something :/

**Comment by nijikon** [comment]
Duplicate #59
