### ISSUE TITLE
The Example Wording cop check for should is case sensitive. 

### ISSUE THREAD

**Issue by EsterYtterbrinkAtTrialbee** [nevir/rubocop-rspec#30]
It would be nice if the Example Wording cop also caught wordings like this:

```rspec
it 'Should do something' do 
```

and not only

```rspec
it 'should do something' do  
```

**Comment by geniou** [comment]
@EsterYtterbrinkAtTrialbee so you mean, that it should start with an capital letter?

Good idea. Feel free to create a pull request - otherwise I'm not sure when I find the time to do this.
