### ISSUE TITLE
Change InstanceVariable cop to check for `ivasgn`

### ISSUE THREAD

**Issue by wbotelhos** [nevir/rubocop-rspec#34]
While testing Devise controllers we do something like:

```ruby
@request.env['devise.mapping'] = Devise.mappings[:user]
```

or

```ruby
@controller.instance_variable_set :@current_user, user
```

Then:

`RSpec/InstanceVariable: Use let instead of an instance variable`

But the variables `@request` and `@controller` were not created by me, so a white list would be welcome here. What do you think?

**Comment by geniou** [comment]
Good point. I had other case where this cop was producing a "false alert". Maybe it would be an idea only do report if an instance variable is assigned e.g. `@foo = :bar` and not in cases as you described and not if the variable is only read. I take a look. Thanks for the report.

**Comment by wbotelhos** [comment]
> Maybe it would be an idea only do report if an instance variable is assigned e.g. `@foo = :bar`

Looks great.

**Comment by ehannes** [comment]
Any progress on this?

I have a similar problem connected to the ``Use let instead of an instance variable``.

When using shared examples and sending for instance an array as an argument, I would like to be able to first declare the array, then do the function call. Like this:

```
@invalid_emails = ['mailable@invaliddomain',  'mailable_at_noatsign.org',
                               'test.mailable@invaliddomain.', 'mailable@invalid_domain.com',
                               'mailable@in+validdomain.com', 'mailable@test..com']
it_behaves_like 'email validation', @invalid_emails
```

Would this be possible?

**Comment by backus** [comment]
@wbotelhos try out master. I've add an `AssignmentOnly` configuration option
