### ISSUE TITLE
RSpec/VerifiedDoubles is overaggressive when nothing stubbed

### ISSUE THREAD

**Issue by CJBridges** [nevir/rubocop-rspec#35]
Note: no tests actually run.  May be dumb error in code.

I'm writing a class which is used for plumbing a single value.  In the real world, this class takes 4 values, processes 3 of them, and passes one of them through unchanged.

```ruby
def MyService
  def initialize(opaque_obj)
    @opaque_obj = opaque_obj
  end

  def call
    my_internal_service.new(@opaque_obj).call
  end

  private

  def my_internal_service  # for stubbing
    MyInternalService
  end
end
```

A spec for this could look something like...
```ruby
describe 'MyService' do
  let(:opaque_obj) { double(:opaque_obj) }  # uh oh, verified double checker....
  let(:my_internal_service) { class_double('MyInternalService') }
  let(:retval) { true }
  subject { MyService }

  before do
    allow(subject).to_receive(my_internal_service).and_return(my_internal_service) # stub external dependency
  end

  it 'passes var to MyInternalService'
    # assert that input made it to correct spot in output.
    expect(my_internal_service).to receive('new').with(opaque_obj).and_return(retval)

    #and verify that my service passes the retval back
    expect(subject.new(opaque_obj).call).to eq(retval)
  end
end
```

So we have a case where we want to pass a class through, but treat it as an opaque object, never calling anything on it, modifying it, or even looking at it.  From a double perspective, we shouldn't care about being a verifying double or what type it is at all.  Keeping a notation in the spec that we're expecting a non-specific class is valuable, but there's no value in verifying it's an instance of a specific class (could be a variety, perhaps unrelated. Go duck typing!)

*Proposed fix*:
  - if no stubbed methods, expects, or allows applied to the double, let it be!  No errors.

*Workaround*:
  - Use '' (or similar constant) as the value instead.  This loses the information that it's really a class typically being passed through.  Can also mess with equality checks later if you're fast and loose with reference vs. value equality.

**Comment by CJBridges** [comment]
P.S. These were real world problems encountered while trying to enable the verified double checker (which I heartily approve of!)

**Comment by andyw8** [comment]
Hi @CJBridges 

I was the author of that cop, but I've only just seen your message today.

I agree fully that there is no point in using a verified double if nothing is being stubbed.

To permit a non-verifying double, we'd need to ensure several things:

* There is no hash supplied when creating the double, e.g. `double(:widget, foo: "bar")`
* There are no `allow`s on the double, e.g. `allow(widget).to receive(...)`
* There are no `expect`s on the double, , e.g. `expect(widget).to receive(...)`

Have I missed anything?

**Comment by CJBridges** [comment]
I think that covers the cases for doubles.  There's also the related `spy` set of errors if something is not an `instance_spy`.

**Comment by andyw8** [comment]
I had a look into this and I think it's difficult to do using static analysis.

Detecting a direct call to `allow` or `expect` is ok, but that could also happen in a helper method, e.g.:

```
it do
  foo = double('Widget')
  stub_price(widget, 1)
  expect(widget.price).to eq(1)
end

def stub_price(widget, amount)
  allow(widget).to receive(:price).and_return(amount)
end
```

I can't think of any reliable way to implement that. I could be wrong, my experience with parsers and ASTs is limited.

So I'm thinking it may be better to relax the cop, so that if only runs if you pass a string or constant as the double name, and it ignores doubles with symbols for names.

**Comment by CJBridges** [comment]
The rule seems reasonable (I'd probably use it), but significantly weakens the cop.

As such, I suggest making it a configurable option such as:
```
RSpec/VerifiedDoubles:
  EnforcedStyle: allow_doubles_of_symbols
```

Also remember that `double` is valid without an argument, but I think the checker should reject it as inappropriate.
`let(:my_random_double) { double }`

**Comment by andyw8** [comment]
Good point. Not sure about the name though, kind of sounds like we are making a double of the symbol itself. How about `ignore_symbolic_names`?

**Comment by CJBridges** [comment]
Naming things is always tough.  I feel like `ignore_symbolic_names` is a good choice.

**Comment by backus** [comment]
@andyw8 It is alright to close this, correct?

**Comment by andyw8** [comment]
Yes, I believe this is fully resolved now.
