### ISSUE TITLE
Build is broken?

### ISSUE THREAD

**Issue by andyw8** [nevir/rubocop-rspec#38]
Travis shows that the build has been broken since "about a month ago". I'm seeing similar failures locally when trying to run the test suite.

**Comment by geniou** [comment]
Hi @andyw8, I know about this. It looks like `rubocop` has changed the way their tests are written and so `rubocop-rspec` needs to adapt.

So fare I didn't found the time to adapt the tests. It would be great if you / somebody can prepare a pull request to fix this.

**Comment by andyw8** [comment]
I'm looking into it. 0.29.1 is fine, it seems to be 0.30.0 that broke it.

**Comment by bquorning** [comment]
Probably becasue bbatsov/rubocop@5e8199ed0b3f6cf50cb63a59311278eebc8683fa removed all spec files from the distributed gem. So now [the spec helper](https://github.com/nevir/rubocop-rspec/blob/master/spec/spec_helper.rb#L6) doesn’t load any of RuboCop’s spec support files.

**Comment by bquorning** [comment]
Maybe a `git clone --depth 1 <rubocop repos> vendor/rubocop` will work? I’ll try making a PR.

**Comment by geniou** [comment]
Fixed with #39
