### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by agrimm** [nevir/rubocop-rspec#40]
RuboCop has some metrics cops, such as "Metrics/MethodLength" which checks how long methods are.  Should RuboCop-rspec have configurable metrics such as "it statements should be no more than 10 lines long", or "it statements should have no more than 5 local variables", or "it statements should have only one expect"?

**Comment by andyw8** [comment]
:+1:

A rule for a maximum level of nesting would also be helpful.

**Comment by geniou** [comment]
@agrimm nice idea - I like it.

For now I don't have an idea what good values would be - so if 5 lines are enough or 10 is more realistic, but maybe we can start a discussion here and see if we find a consents and then create a check for this.

**Comment by andyw8** [comment]
Assuming a test follows the "arrange, act, assert" pattern, the *act* and *assert* phases would need one line each, so the remainder would be the *arrange* phase. I think allowing 5 lines for that would be a reasonable default, giving a default maximum of 7 lines.

**Comment by andyw8** [comment]
I've made a first attempt at this in #85.

**Comment by backus** [comment]
@andyw8 implemented the `ExampleLength` cop. I'll open issues for "maximum level of nesting" + "one expect per `it`". After that I will close this issue. Please object if you think I missed something

**Comment by backus** [comment]
@agrimm check out the new issues and let me know how you would improve the them. Closing this issue now in favor of the more specific issues I've opened. Both reference this issue for additional context
