### ISSUE TITLE
RSpec/DescribeClass should not apply to View specs

### ISSUE THREAD

**Issue by gerry3** [nevir/rubocop-rspec#47]
Currently, using the standard describe format for [View specs](https://www.relishapp.com/rspec/rspec-rails/v/3-3/docs/view-specs/view-spec):
`RSpec.describe "widgets/index" do`
we get:
`The first argument to describe should be the class or module being tested.`

I'm disabling it for now:
`RSpec.describe "widgets/index" do # rubocop:disable RSpec/DescribeClass`

But the `RSpec/DescribeClass` cop should probably ignore View specs.

**Comment by geniou** [comment]
For now you could disable this cop for the view spec folder (I guess its `spec/views`) in the [.rubocop.yml](https://github.com/nevir/rubocop-rspec#the-cops). We could think about having this configuration as default for this cop.

Let me know if this helped you.

**Comment by gerry3** [comment]
Yes, that's a better workaround and it works great with rubocop from the command line. For some reason my editor integration isn't respecting the config, but that's no big deal. Thanks!

**Comment by pgolm** [comment]
:+1:

**Comment by nijikon** [comment]
Did run to this issue today. Actually it's a pity that rspec does not have ```type: :view``` it would solve this easily.

**Comment by andyw8** [comment]
@nijikon: There is a `view` type:

https://www.relishapp.com/rspec/rspec-rails/docs/directory-structure

It would be optional if `infer_spec_type_from_file_location!` was set, but the newer versions of rspec-rails seem discourage using that configuration.

**Comment by andyw8** [comment]
I've opened PR #90 to address this.
