### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by mjgiarlo** [nevir/rubocop-rspec#48]
I see that there are bugs in v1.3.0 that have since been fixed in master, namely how `#autocorrect` no longer appends to `@corrections`. Could you release a new version of rubocop-rspec with this fix?

**Comment by grosscol** [comment]
+1

**Comment by geniou** [comment]
Sorry - I forgot this. I'm going to do this as soon as possible. Thanks for the reminder.

**Comment by mjgiarlo** [comment]
👍

**Comment by geniou** [comment]
Sorry for the delay, but I released a new version: https://github.com/nevir/rubocop-rspec/releases/tag/v1.3.1

**Comment by mjgiarlo** [comment]
:clap: @geniou
