### ISSUE TITLE
Temporarily disable rspec cop?

### ISSUE THREAD

**Issue by ehannes** [nevir/rubocop-rspec#51]
Is it possible to disable the rspec cop (or specific rules in the rspec cop) as it is with ordinary rubocop rules? For instance:

```
# rubocop:disable InstanceVariable
@bar
it_behaves_like 'foo', @bar
# rubocop:enable InstanceVariable
```

@bar could be a long array or something similar that I do not want to declare in the function call to 'foo'.

**Comment by ehannes** [comment]
Found it!

```
# rubocop:disable RSpec/InstanceVariable
# rubocop:enable RSpec/InstanceVariable

Maybe this could be included in the readme file?

**Comment by bar** [comment]
@ehannes ahh?

**Comment by ehannes** [comment]
Sorry?

**Comment by andyw8** [comment]
@ehannes you mentioned `@bar` in your comment, and GitHub assumed you were referring to the user with that name.

**Comment by ehannes** [comment]
Sorry!
