### ISSUE TITLE
Put `subject` at the top of its context block

### ISSUE THREAD

**Issue by backus** [nevir/rubocop-rspec#52]
When using subject it should be at the top of its context block, ideally separated by one blank line from any `let`s, `before`s, or `it`s.  

**good**
```ruby
RSpec.describe SomeClass do
  subject { described_class.new(foo, bar) }

  let(:foo) { 'foo' }
  let(:bar) { 'bar' }
end
```

**bad**
```ruby
RSpec.describe SomeClass do
  let(:foo) { 'foo' }
  let(:bar) { 'bar' }
  subject { described_class.new(foo, bar) }
end
```

thoughts?  Happy to do a PR

**Comment by andyw8** [comment]
I'm not saying it's good, but the majority of specs I see 'in the wild' tend to have the `let`s before the `subject`.

**Comment by andyw8** [comment]
I spotted that you already implemented this in https://github.com/backus/rubocop-devtools/blob/master/lib/rubocop/cop/devtools/leading_subject.rb
