### ISSUE TITLE
Contexts without any tests

### ISSUE THREAD

**Issue by agrimm** [nevir/rubocop-rspec#56]
In the following code, I accidentally created a context without any tests, because the `it 'is chunky'` is after the context has ended.

    describe Bacon do
      let(:bacon) { Bacon.new(chunkiness) }
      let(:chunkiness) { false }
      context 'extra chunky' do
        let(:chunkiness) { true }
      end

      it 'is chunky' do
        expect(bacon.chunky?).to be_truthy
      end
    end

Contexts without any tests should generate an offense.

**Comment by nijikon** [comment]
:+1:

**Comment by backus** [comment]
Interesting. I wish it was easy for us to have a namespace of our own like RuboCop does. Then this could be classified as `RSpec/Lint/EmptyContext`

**Comment by backus** [comment]
This is in master now
