### ISSUE TITLE
"Use let instead of an instance variable" in `before(:all)` 

### ISSUE THREAD

**Issue by conzett** [nevir/rubocop-rspec#57]
Currently when using an instance variable in a `before(:all)` or an `after(:all)` call you get the usual:

```shell
C: Use let instead of an instance variable
```

However if you change it over to a `let` instead of an ivar, RSpec will throw the following warning:

```shell
`let` and `subject` declarations are not intended to be called
in an `after(:context)` hook, as they exist to define state that
is reset between each example, while `after(:context)` exists to
cleanup state that is shared across examples in an example group.
```

I'm inclined to agree with RSpec in this case but I'm looking for feedback, thanks!

**Comment by andyw8** [comment]
I don't think there's much that rspec-rubocop can do in this situation. It reports the problem, but it assumes a basic understanding of RSpec to fix it.

**Comment by mockdeep** [comment]
@conzett `let` and `subject` come at a higher level, outside your `before` block:

```ruby
describe 'something' do
  let(:a_thing) { Thing.new }

  before do
    # any setup
  end

  it 'does stuff' do
    expect(a_thing.do_stuff).to eq 'stuff'
  end
end
```

More in the docs here: https://www.relishapp.com/rspec/rspec-core/v/3-1/docs/helper-methods/let-and-let

**Comment by conzett** [comment]
@mockdeep I'm aware of that, perhaps my initial example was unclear. This demonstrate the issue:

```ruby
describe 'something' do
  let(:a_thing) { Thing.new }

  before(:all) do
    # This should be shared for all specs
    # Rubocop rspec is not happy
    @clean_me_up_later = { some: :thing }
  end
end
```

The RSpec warning above does say:
```shell
`after(:context)` exists to cleanup state that is shared
across examples in an example group
```

I think discouraging ivars in general makes sense, especially inside `describe`s, but can there be an exception for things like `before(:all)`? [The docs themselves show this](https://www.relishapp.com/rspec/rspec-core/docs/hooks/before-and-after-hooks).

**Comment by mockdeep** [comment]
Hmm, can you give me more details on what you're trying to achieve with this? I suspect there's a way to do it either without the ivar or without the `before(:all)`. The `before(:all)` approach introduces shared state across your specs, which can cause them to be inconsistent if they interact with the ivar set up there. One option is to use a `before(:each)` instead, or you might just define your thing as a constant at the top of your spec:

```ruby
describe 'something' do
  let(:a_thing) { Thing.new }
  MY_SHARED_CONST = 'foo'

  it 'does stuff' do
    expect(a_thing.do_stuff(MY_SHARED_CONST)).to eq 'stuff'
  end
end
```

Worst case, though, you can always disable the rule selectively if you like:

```ruby
@my_shared_var.do_stuff # rubocop:disable RSpec/InstanceVariable
```

Or entirely in your `.rubocop.yml` file:

```yaml
RSpec/InstanceVariable:
  Enabled: false
```

**Comment by andyw8** [comment]
How about an extra configuration option `IgnoreBeforeAllBlocks`?

**Comment by backus** [comment]
Not sure about a special case config option here. Since @conzett didn't followup with @mockdeep I'll close for now. In my opinion this is exactly what `rubocop:disable` is for.
