### ISSUE TITLE
Cop suggestion: Checks for Gherkin/Cucumber-style scenarios

### ISSUE THREAD

**Issue by andyw8** [nevir/rubocop-rspec#95]
I've seen a number of teams adopt this style for writing feature specs:
https://about.futurelearn.com/blog/how-we-write-readable-feature-tests-with-rspec/

There's a few things that it would be useful to have checks for:
* Each line should begin with a valid Gherkin term ('given_', 'when_', 'then_', 'and_' or 'but_')
* Configurable maximum number of lines per clause (e.g. 3 for a `when_`) to encourage readability.
* Presence of at least one 'when_' and one 'then_' per scenario ('given_' can be optional)

**Comment by backus** [comment]
Honestly this is a bit odd for my tastes if you are suggesting writing something like this:

```ruby
feature 'Enrolment' do
  scenario 'Enrolling in a course' do
    given_there_is_a_course
    and_i_am_logged_in_as_a_learner
    when_i_enrol_on_a_course
    then_the_course_should_appear_in_my_courses
  end

  def given_there_is_a_course
    @course = FactoryGirl.create(:course)
  end

  def and_i_am_logged_in_as_a_learner
    @learner = FactoryGirl.create(:learner)
    login_as @learner
  end

  def when_i_enrol_on_a_course
    visit course_path(@course)
    find('.join').click
    expect(page).to have_content('Thanks for joining!')
  end

  def then_the_course_should_appear_in_my_courses
    visit '/'
    expect(page).to have_main_header('My Courses')
    expect(page).to have_content(@course.full_title)
  end
end
```

@andyw8 could you weigh in on exactly what you want to support/encourage and possibly make a counter-argument about this being in scope for rubocop-rspec if you disagree with me?

**Comment by andyw8** [comment]
Yeah, maybe this approach isn't widely used enough to justify adding support for it. I'm not involved with that particular project any more, so I don't feel strongly about it.

**Comment by backus** [comment]
Alright. Given that neither of us particularly care for this test style (and even if we did I still don't think it would make sense for rubocop-rspec) I'm going to close this issue. Thanks for sharing though I did find the fact that people use rspec like this interesting
